### PR TITLE
Feature/send raw message thorugh flow

### PR DESCRIPTION
**Pull request by davidtorellineueda**
Solving #20 
Send raw message through transformation flow.

### CODE REVIEW

**Comment by colinpattison** [comment]
Hey David - can you  provide some more information on what this change is actually providing/adding?

C

**Comment by davidtorellineueda** [comment]
@colinpattison , you can find a description at attached issue #20 
If this is not clear enough I can do some more documentation to clarify.
There are two fixtures with examples about creating flows and sending information using FIX notation (send raw). 

Cheers!

**Comment by MrTam** [comment]
Hey David - really sorry for the delay on this - been a very busy couple of weeks..I'll try get this done today for you!

**Comment by davidtorellineueda** [comment]
Hi @MrTam, did you have time to review this? I would like to introduce this into etiqet since this gives great value when debugging client scenarios where raw messages are provided together with evidences that something went wrong. So ... really good to replicate client support scenarios.

**Comment by davidtorellineueda** [comment]
@MrTam, 
First of all thanks for your feedback 👍 

I understand the DSL stuff, so need to define the concept of a flow in a cucumber way to avoid confusions. So agree on this ... I believe Cucumber give as here a lot of power to start, but also some limitations and maybe in the future we should consider moving into a DSL approach, ... but this is not the question right now... So agree on the DSL comment ;-)
The idea here is to provide a mechanism to run raw data, however, sometimes some of the tags need to be modified to make the test run properly (e.g. timestamp, sequence, ...) and when modifying those, also necessary to change the message length and CRC.
To do that we are hacking the default quickfixj session's reposponder introducing a chain of transformations ... The idea for this is just to make these changes more flexible to the user, but agree that is not user friendly at all, and that names of flow stages are also confusing for the end user.

Maybe we should extend Etiqet language to support extra features in a more natural way, hiding those flows for the end user and start with a default internal flow replacing timestamp, sequence, length and checksum replacement.

So we could leave processing flows as a tool to develope new features regarding the transformation of messages, but not exposed to the final user, since it is hard to understand.

`Then send raw message "8=FIX.4.4|9=74|35=0|....|10=44|"`

This will be most common scenario, but there are some others really interesting (e.g. record/replay) which could be easily done though this processing pipe approach.

Regards,
David

**Comment by davidtorellineueda** [comment]
@MrTam, Maybe we could send explicitly the raw message, including timestamp, sequence, length and checksum, and just add them if they are missing ... What do you think?

**Comment by colinpattison** [comment]
@davidtorellineueda yea i think we need to extend the verbs/embed it into the verbs. 

Having a message replayed that needs certain fields updated is a very common scenario across multiple protocols. Perhaps we add the transformations as a config option? i.e. define functions to pass the message through to generate the final payload IF the user calls "send raw message" similar to the approach taken for generating the timestamp/client order ids in the first place

C

**Comment by MrTam** [comment]
Hey David. just tidying up PRs and issues on the project, noticed this one's still open. Is this something you still would like merged in?

**Comment by MrTam** [comment]
Closing this for now...we can reopen/revisit if required. Thanks David!

**Pull request closed without merging**
